- name: configure frontend component
  hosts: frontend
  become: yes
  tasks:

  - name: disable default nginx module
    ansible.builtin.command: dnf module disable nginx -y
    ignore_errors: yes

  - name: enable nginx 1.24 module
    ansible.builtin.command: dnf module enable nginx:1.24 -y
    ignore_errors: yes

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: copy roboshop nginx config
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
      owner: nginx
      group: nginx
      mode: '0755'

  - name: download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: validate nginx config
    ansible.builtin.command: nginx -t

  - name: restart and enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
